# Generated by Django 6.0 on 2025-12-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=20)),
                ('logger', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'radius_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
