"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (project root is one level up from backend)
ENV_FILE = BASE_DIR.parent / '.env'
if ENV_FILE.exists():
    load_dotenv(ENV_FILE)
elif not os.environ.get('SECRET_KEY'):
    # In production (Docker), env vars are already set via docker-compose env_file
    # Only warn if running locally without .env AND without env vars set
    import sys
    if 'runserver' in sys.argv or 'manage.py' in sys.argv[0]:
        print(f"Warning: .env file not found at {ENV_FILE}")


def get_env_variable(var_name, default=None, required=True, cast=None):
    """
    Get environment variable or raise exception if required and missing.
    
    Args:
        var_name: Name of the environment variable
        default: Default value if not required and missing
        required: If True, raises ImproperlyConfigured when variable is missing
        cast: Type to cast the value to (str, int, bool, etc.). None means str.
    
    Returns:
        The environment variable value, cast to the specified type
    
    Raises:
        ImproperlyConfigured: If required variable is missing
    """
    value = os.environ.get(var_name)
    
    if value is None:
        if required and default is None:
            raise ImproperlyConfigured(
                f"Required environment variable '{var_name}' is not set. "
                f"Please check your .env file at {ENV_FILE}"
            )
        value = default
    
    # Handle type casting
    if value is not None:
        if cast == bool:
            return str(value).lower() in ('true', '1', 'yes')
        elif cast == int:
            return int(value)
        elif cast is None or cast == str:
            return str(value)
        return cast(value)
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_variable('DEBUG', cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    # Custom apps
    'users',
    'nas',
    'sessions',
    'radius',
    'stats',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend_dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'frontend_dist',
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth User Helper
AUTH_USER_MODEL = 'users.AdminUser'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardResultsSetPagination',
}

# Simple JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


# =============================================================================
# RADIUS Server Configuration
# =============================================================================

RADIUS_CONFIG = {
    # Authentication port (RFC 2865)
    'AUTH_PORT': get_env_variable('AUTH_PORT', cast=int),
    # Accounting port (RFC 2866)
    'ACCT_PORT': get_env_variable('ACCT_PORT', cast=int),
    # Server bind address (0.0.0.0 for all interfaces)
    'BIND_ADDRESS': get_env_variable('BIND_ADDRESS'),
    # Logging level
    'LOG_LEVEL': get_env_variable('LOG_LEVEL'),
    # Path to RADIUS dictionary file
    'DICTIONARY_PATH': BASE_DIR / 'radius' / 'dictionary',
    # Accounting interim interval (RFC 2869)
    'ACCT_INTERIM_INTERVAL': get_env_variable('ACCT_INTERIM_INTERVAL', cast=int),
    # Max inactive sessions to retain in DB
    'MAX_INACTIVE_SESSIONS': get_env_variable('RADIUS_INACTIVE_SESSION_DB_RETENTION_LIMIT', cast=int),
    # Multiplier for ACCT_INTERIM_INTERVAL to consider a session dead/stale
    'STALE_SESSION_MULTIPLIER': get_env_variable('RADIUS_STALE_SESSION_MULTIPLIER', cast=int),
}

# =============================================================================
# Statistics Configuration
# =============================================================================

STATS_CONFIG = {
    # Interval for saving server-wide active sessions stats (in seconds)
    'SERVER_SESSIONS_INTERVAL': get_env_variable('STATS_SERVER_SESSIONS_INTERVAL', default=300, required=False, cast=int),
    # Interval for saving server-wide traffic stats (in seconds)
    'SERVER_TRAFFIC_INTERVAL': get_env_variable('STATS_SERVER_TRAFFIC_INTERVAL', default=300, required=False, cast=int),
    # Interval for saving per-user active sessions stats (in seconds)
    'USERS_SESSIONS_INTERVAL': get_env_variable('STATS_USERS_SESSIONS_INTERVAL', default=300, required=False, cast=int),
    # Interval for saving per-user traffic stats (in seconds)
    'USERS_TRAFFIC_INTERVAL': get_env_variable('STATS_USERS_TRAFFIC_INTERVAL', default=300, required=False, cast=int),
}

# Logging Configuration
RADIUS_LOG_RETENTION = get_env_variable('RADIUS_LOG_RETENTION', cast=int)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'db_log': {
            'level': 'DEBUG',
            'class': 'radius.logging_handler.DatabaseLogHandler',
        },
    },
    'root': {
        'handlers': ['console', 'db_log'],
        'level': get_env_variable('LOG_LEVEL'),
    },
}
