# Generated by Django 6.0 on 2025-12-04 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, help_text='Unique identifier for the NAS (matches NAS-Identifier attribute)', max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the NAS')),
                ('shared_secret', models.CharField(help_text='Shared secret for RADIUS authentication', max_length=128)),
                ('auth_port', models.PositiveIntegerField(default=1812, help_text='Authentication port', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('acct_port', models.PositiveIntegerField(default=1813, help_text='Accounting port', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the NAS is active')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the NAS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NAS Client',
                'verbose_name_plural': 'NAS Clients',
                'db_table': 'radius_nas_clients',
                'ordering': ['identifier'],
                'unique_together': {('identifier', 'ip_address')},
            },
        ),
    ]
