# Generated by Django 6.0 on 2025-12-04 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Unique session identifier (Acct-Session-Id)', max_length=64)),
                ('username', models.CharField(db_index=True, help_text='Username of the connected user', max_length=64)),
                ('nas_identifier', models.CharField(blank=True, default='', help_text='Identifier of the NAS', max_length=64)),
                ('nas_ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the NAS', null=True)),
                ('framed_ip_address', models.GenericIPAddressField(blank=True, help_text='IP address assigned to the VPN client', null=True)),
                ('calling_station_id', models.CharField(blank=True, default='', help_text='Client identifier (MAC address or IP)', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped')], db_index=True, default='active', help_text='Current session status', max_length=16)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the session started')),
                ('stop_time', models.DateTimeField(blank=True, help_text='When the session ended', null=True)),
                ('session_time', models.PositiveIntegerField(default=0, help_text='Total session duration in seconds')),
                ('input_octets', models.BigIntegerField(default=0, help_text='Bytes received from client')),
                ('output_octets', models.BigIntegerField(default=0, help_text='Bytes sent to client')),
                ('input_packets', models.BigIntegerField(default=0, help_text='Packets received from client')),
                ('output_packets', models.BigIntegerField(default=0, help_text='Packets sent to client')),
                ('terminate_cause', models.PositiveSmallIntegerField(blank=True, help_text='Reason for session termination (RFC 2866)', null=True)),
            ],
            options={
                'verbose_name': 'RADIUS Session',
                'verbose_name_plural': 'RADIUS Sessions',
                'db_table': 'radius_sessions',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['username', 'status'], name='radius_sess_usernam_ccf6ec_idx'), models.Index(fields=['nas_ip_address', 'status'], name='radius_sess_nas_ip__2522f0_idx')],
                'unique_together': {('session_id', 'nas_ip_address')},
            },
        ),
    ]
