# Generated by Django 6.0 on 2025-12-07 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiussession',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the session was updated'),
        ),
    ]
