# Generated by Django 6.0 on 2025-12-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Unique username for authentication', max_length=64, unique=True)),
                ('password_hash', models.CharField(help_text='Bcrypt hashed password', max_length=128)),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=1, help_text='Maximum number of concurrent VPN sessions allowed')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Optional expiration date for the account', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about the user')),
                ('current_sessions', models.PositiveIntegerField(default=0, help_text='Current number of active sessions')),
                ('remaining_sessions', models.IntegerField(default=1, help_text='Remaining allowed sessions')),
            ],
            options={
                'verbose_name': 'RADIUS User',
                'verbose_name_plural': 'RADIUS Users',
                'db_table': 'radius_users',
                'ordering': ['username'],
            },
        ),
    ]
