# Generated by Django 6.0 on 2025-12-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiususer',
            name='rx_traffic',
            field=models.BigIntegerField(default=0, help_text='Total bytes received (download)'),
        ),
        migrations.AddField(
            model_name='radiususer',
            name='total_traffic',
            field=models.BigIntegerField(default=0, help_text='Total traffic (rx + tx)'),
        ),
        migrations.AddField(
            model_name='radiususer',
            name='tx_traffic',
            field=models.BigIntegerField(default=0, help_text='Total bytes sent (upload)'),
        ),
    ]
