# Generated by Django 6.0 on 2025-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_radiususer_rx_traffic_radiususer_total_traffic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiususer',
            name='allowed_traffic',
            field=models.BigIntegerField(blank=True, help_text='Maximum allowed traffic in bytes (NULL for unlimited)', null=True),
        ),
    ]
