# Generated by Django 6.0 on 2025-12-07 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsServerActiveSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this stat was recorded')),
                ('active_sessions', models.PositiveIntegerField(default=0, help_text='Total number of active sessions at this time')),
            ],
            options={
                'verbose_name': 'Server Active Sessions Stat',
                'verbose_name_plural': 'Server Active Sessions Stats',
                'db_table': 'stats_server_active_sessions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='stats_serve_timesta_51a22a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatsServerTotalTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this stat was recorded')),
                ('total_rx', models.BigIntegerField(default=0, help_text='Total bytes received (download) across all users')),
                ('total_tx', models.BigIntegerField(default=0, help_text='Total bytes sent (upload) across all users')),
                ('total_traffic', models.BigIntegerField(default=0, help_text='Total traffic (rx + tx) across all users')),
            ],
            options={
                'verbose_name': 'Server Total Traffic Stat',
                'verbose_name_plural': 'Server Total Traffic Stats',
                'db_table': 'stats_server_total_traffic',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='stats_serve_timesta_bfb2e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatsUsersActiveSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this stat was recorded')),
                ('username', models.CharField(db_index=True, help_text='Username of the user', max_length=64)),
                ('active_sessions', models.PositiveIntegerField(default=0, help_text='Number of active sessions for this user at this time')),
            ],
            options={
                'verbose_name': 'User Active Sessions Stat',
                'verbose_name_plural': 'User Active Sessions Stats',
                'db_table': 'stats_users_active_sessions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', '-timestamp'], name='stats_users_usernam_ebb4da_idx'), models.Index(fields=['-timestamp'], name='stats_users_timesta_08c489_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatsUsersTotalTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this stat was recorded')),
                ('username', models.CharField(db_index=True, help_text='Username of the user', max_length=64)),
                ('rx_traffic', models.BigIntegerField(default=0, help_text='Total bytes received (download) by this user')),
                ('tx_traffic', models.BigIntegerField(default=0, help_text='Total bytes sent (upload) by this user')),
                ('total_traffic', models.BigIntegerField(default=0, help_text='Total traffic (rx + tx) for this user')),
            ],
            options={
                'verbose_name': 'User Total Traffic Stat',
                'verbose_name_plural': 'User Total Traffic Stats',
                'db_table': 'stats_users_total_traffic',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', '-timestamp'], name='stats_users_usernam_5f8505_idx'), models.Index(fields=['-timestamp'], name='stats_users_timesta_3bc5cf_idx')],
            },
        ),
    ]
